# roles/windows_win_iis_webapppool/tasks/main.yml
---

- name: Start existing application pool
  community.windows.win_iis_webapppool:
    name: "{{ item.pool }}"
    state: started
  loop: "{{ IIS_POOL }}"
